[package]
name = "jb_common"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-subscriber.features = ["fmt", "json"]

[features]
local-testing = ["tracing-subscriber/ansi"]
